### ISSUE TITLE
What's the differences with MTCNN?

### ISSUE THREAD

**Issue by inlmouse** [Jack-CV/PCN#2]
With the similar architecture of MTCNN, you did not even mention it in your paper? Where is the highlight of this work? Just re-train the 3 nets in MTCNN and sightly modify the test code, we can get the same results and higher fps than your paper.

**Comment by Jack-CV** [comment]
@inlmouse Thanks for your interest in our work. As we know, [Cascade CNN in CVPR 2015](https://www.cv-foundation.org/openaccess/content_cvpr_2015/papers/Li_A_Convolutional_Neural_2015_CVPR_paper.pdf) is the first work that uses three stages of CNNs to detect faces. Both MT-CNN and our PCN are based on the work of Cascade CNN, while these two works aim to solve different problems in face detection, leading to similar but clearly distinct architectures. The motivation of MT-CNN is to take advantages of multiple relevant tasks to improve accuracy on generic face detection, and thus it simply adds to each CNN two branches for bounding box and landmark prediction. By contrast, our PCN focuses on **robustly detecting faces within full range of 360 degrees of in-plane rotation**, leading to the design of **progressively calibrating rotated faces stage by stage** to efficiently handle large appearance variations of them. The calibration tasks of different CNNs in our PCN are logically connected, which is more than combining multiple tasks.

Indeed, MT-CNN is a good work on face detection and we have cited MT-CNN in our paper (Reference [23]). We do not provide independent discussions on MT-CNN, since it addresses a different problem and there are other works more relevant to ours, i.e. aiming to solve rotation-variant face detection, which are extensively discussed and compared in our paper.

The highlight of our PCN is the **progressive calibration mechanism** that can **improve the accuracy of rotation-invariant face detection obviously with little time cost**. According to our experimental results, advanced detectors using much larger networks, e.g. Faster R-CNN/R-FCN/SSD using VGG-16/ResNet-50, lags behind our PCN in terms of recall when producing a reasonable number of false positives. And the baseline Cascade CNN is significantly outperformed by our PCN. Therefore, it is less likely that simply re-training MT-CNN with rotation augmented faces can obtain the same accuracy on **rotation-invariant face detection task** but running at higher speed. If you can provide quantitative experimental results of directly training MT-CNN on rotated faces, we will be very glad for further discussions.

**Comment by jnulzl** [comment]
Having some different with MTCNN.
In all,great works!

**Comment by Jack-CV** [comment]
@jnulzl Thanks for your appreciation on our work.
